package com.admin;

import javax.persistence.Entity;

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class Admin {
	@Id  //To Identify the entity with generated unique key.
	@GeneratedValue(strategy = GenerationType.AUTO)   //here keys are generated by the hibernate 
		private int id;
		private String email;
		private String uName;
		private String pass;

		public String getEmail() {
			return email;
		}

		public void setEmail(String email) {
			this.email = email;
		}

		public String getuName() {
			return uName;
		}

		public void setuName(String uName) {
			this.uName = uName;
		}

		public String getPass() {
			return pass;
		}

		public void setPass(String pass) {
			this.pass = pass;
		}

		@Override
		public String toString() {
			return "Admin [email=" + email + ", uName=" + uName + ", pass=" + pass + "]";
		}

	}

